### ISSUE TITLE
1 test fails

### ISSUE THREAD

**Issue by yurivict** [beartype/beartype#261]
```
=================================== FAILURES ===================================
_____________________________ test_coerce_hint_any _____________________________

    def test_coerce_hint_any() -> None:
        '''
        Test the private
        :func:`beartype._check.convert.convcoerce.coerce_hint_any` coercer.
        '''
    
        # ..................{ IMPORTS                            }..................
        # Defer test-specific imports.
        from beartype._check.convert.convcoerce import coerce_hint_any
        from beartype._util.py.utilpyversion import (
            IS_PYTHON_AT_LEAST_3_10,
            IS_PYTHON_AT_LEAST_3_9,
        )
    
        # ..................{ CORE                               }..................
        # Assert this coercer preserves an isinstanceable type as is.
        assert coerce_hint_any(int) is int
    
        # ..................{ PEP 585                            }..................
        # If the active Python interpreter targets Python >= 3.9 and thus supports
        # PEP 585...
        if IS_PYTHON_AT_LEAST_3_9:
            # Arbitrary PEP 585-compliant type hint.
            hint_pep585 = list[int]
   
            # Assert this coercer preserves the first passed instance of a PEP
            # 585-compliant type hint as is.
>           assert coerce_hint_any(hint_pep585) is hint_pep585
E           assert list[int] is list[int]
E            +  where list[int] = <function coerce_hint_any at 0x9712688b0>(list[int])

beartype_test/a00_unit/a60_check/a20_conv/test_convcoerce.py:92: AssertionError
=========================== short test summary info ============================
SKIPPED [1] beartype_test/a90_func/z90_lib/a90_nuitka/test_nuitka.py:31: Command "gcc" not found.
SKIPPED [1] beartype_test/a00_unit/a70_decor/a40_code/a90_pep/test_decorpep647.py:21: Python 3.9.17 < 3.10.0.
SKIPPED [1] beartype_test/a00_unit/a70_decor/a40_code/a00_mod/test_decor_contextlib.py:21: Python 3.9.17 < 3.11.0.
SKIPPED [1] beartype_test/a00_unit/a70_decor/a40_code/a90_pep/test_decorpep673.py:21: Python 3.9.17 < 3.11.0.
SKIPPED [1] beartype_test/a00_unit/a70_decor/a40_code/a80_nonpep/mod/test_codepandera.py:22: could not import 'pandera.__init__': No module named 'pandera'
SKIPPED [1] beartype_test/a90_func/pep/test_pep561_static.py:169: Command "pyright" not found.
================== 1 failed, 288 passed, 6 skipped in 31.12s ===================
*** Error code 1


```

Version: 0.15.0
Python-3.9
FreeBSD 13.2

**Comment by leycec** [comment]
**Bizarreness.** Clearly, FreeBSD is stranger even than I dared to contemplate. Thankfully, [our test suite routinely passes under all officially supported platforms](https://github.com/beartype/beartype/actions) – including Linux, macOS, and Windows. Unthankfully, I have *no* reasonable means of testing migraine-inducing *BSD issues at the moment. I don't have a \*BSD machine or VM at the moment; I barely have sufficient volunteer time to maintain @beartype on the three platforms we *do* officially support.

Allow me to wave my hands wildly about. Our continuous integration (CI) pipelines leverage GitHub Actions. That's good. [GitHub Actions currently fails to offer a FreeBSD runner](https://github.com/actions/runner-images/discussions/7109). That's bad. Without official support from Microsoft here, it's unclear either how or when exactly @beartype will be able to support Linux-adjacent platforms like FreeBSD and NetBSD. I feel the sadness and possible anger you also feel. :disappointed: :rage1: :disappointed_relieved: 

Let's quietly leave this open until Microsoft releases a \*BSD runner to the huddled masses. Until then, please accept my heartfelt apology and a hollow promise to do better by the [Butlerian Jihad of 201 BG](https://dune.fandom.com/wiki/Butlerian_Jihad). <sup>← *...heh.*</sup>

**Comment by yurivict** [comment]
> [...] GitHub Actions currently fails to offer a FreeBSD runner [...]

This isn't true.

[Here](https://github.com/jcelerier/libremidi/actions/runs/5649457339) is an example of CI run set on GitHub that includes FreeBSD CI runs.

**Comment by leycec** [comment]
Well, yes. Technically, you *can* run FreeBSD via third-party actions in simplistic pipelines devoted entirely to FreeBSD. Pragmatically, our pipeline is anything but simplistic; those actions don't appear to offer a usable Docker image that integrates with the standard `strategy/matrix:` approach provided by GitHub Actions.

@beartype needs something standard like this:

```yaml
# In our ".github/workflow/python_test.yml" file:
...

# ....................{ MAIN                               }....................
jobs:
  # ...................{ TESTS                              }...................
  # Job iteratively exercising our test suite against all Python interpreters
  # supported by this package (and also measuring the coverage of that suite).
  tests:
    # ..................{ MATRIX                             }..................
    strategy:
      matrix:
        # List of all platform-specific Docker images to test against,
        # including:
        # * The latest Long-Term Service (LTS) release of Ubuntu Linux, still
        #   the most popular Linux distro and thus a sane baseline.
        # * The latest *whatever* release of Microsoft Windows. Although Linux
        #   and macOS are both POSIX-compliant and thus crudely comparable from
        #   the low-level CLI perspective, Windows is POSIX-noncompliant and
        #   thus heavily divergent from both macOS and Linux.
        # * The latest *whatever* release of Apple macOS. We don't particularly
        #   need to exercise tests on macOS, given the platform's patent
        #   POSIX-compliant low-level similarities to Linux, but... what the
        #   heck. Why not? Since this is the lowest priority, we defer macOS
        #   testing until last.
        platform: [ubuntu-latest, windows-latest, macos-latest]
        # ^------ *THIS IS WHERE @beartype NEEDS A "freebsd-latest" DOCKER IMAGE*
```

For @beartype to support FreeBSD, we *really* need GitHub itself to natively support FreeBSD with a `freebsd-latest` Docker image. Lacking that, it's unclear how exactly we could integrate FreeBSD support into our existing pipeline. We're definitely *not* leaving the confines of the standard `strategy/matrix:` approach. If we did that, we'd basically have to manually generate our entire jobs matrix by hand. It's hard enough maintaining this madness *with* GitHub's combinatorial generation of our jobs matrix against all supported Python versions **+** all supported platforms. I sigh. :face_exhaling:
