### ISSUE TITLE
Docs request: `pytest-beartype` config in `pyproject.toml`

### ISSUE THREAD

**Issue by jamesbraza** [beartype/beartype#327]
Hello beartype. I have a simple request here, adding a snippet to the `pytest-beartype` docs about configuring `pytest-beartype` from `pyproject.toml`.

Specifically, should the TOML contain dashes or underscores?

```toml
beartype_packages = ["mypackage"]
# or
beartype-packages = ["mypackage"]
```

The answer is it should be `beartype_packages`. Though I had to figure this out, so it would be nice to make some docs on it. Thank you in advance!
